### ISSUE TITLE
How to send a direct message?

### ISSUE THREAD

**Issue by gmaclennan** [aeirola/slack-irc-client#10]
According to the docs:

> If you want to initiate a 1-to-1 chat with an IRC user that has not yet sent you an message, you need to create a new Slack group chat with the nick of the IRC user you want to contact.

I can't see how to create a new Slack group chat with the nick of the IRC user. As per instructions I am the only person in the Slack org. I understand the way to create group chats is by creating a new Slack Direct Message, and I can only do that with myself or Slackbot.

**Comment by aeirola** [comment]
Yeah, due to technical limitations, Slack doesn't allow you to start direct messages with non-existing users. To circumvent this limitation, slack-irc-client uses the Slack private channels as the way to send and receive IRC queries (1-to-1 chats). This way it is easier to separate the different types of chats in the user interface.

The documentation might use the term groups instead of private channels, since that is term used in the Slack API. Understandably this might cause confusion.

**Comment by gmaclennan** [comment]
Ok so you create a private channel with the IRC user name to start a 1-to-1 chat?

**Comment by aeirola** [comment]
Exactly!
