### ISSUE TITLE
Moving NOTICES and server messages out from @slackbot

### ISSUE THREAD

**Issue by Tehnix** [aeirola/slack-irc-client#29]
I was wondering if there was a way we could move notices and server messages out from the slackbot PM. The main motivation behind this is that you cannot mute private messages, and it quickly gets tedious with notifications for server messages or some dude that is new to IRC and uses notices to communicate.

A few ideas,

- Allow it to be mute'able (least preferable)

- Creating a private slack channel for it, so it doesn't overlap with an IRC channel (if possible)

- Throwing the messages into a predefined slack channel that is 99.9% never gonna be taken (like #noticesFromIrcSlackBot or something like that)

Let me know what you think! :)

**Comment by di** [comment]
👍 Totally agree with this. This has been a bit of a pain for me as well.

I wonder if there's a way to keep channel-specific notices in the channels they originate from, rather than all coming from slackbot, or all in another "special" channel? Similar to how join messages are displayed.

I think this would cut down on most of the annoying DM noise from slackbot and leave just the server messages (which could be configured to be ignored).

**Comment by Tehnix** [comment]
That's actually a good idea, and I think that shouldn't take too much. Looking at https://github.com/aeirola/slack-irc-client/blob/master/lib/irc-handler.js#L241 it seems we could move the bits from https://github.com/aeirola/slack-irc-client/blob/master/lib/irc-handler.js#L233 into the `notice` call, dispatching to a channel instead.

I'll make a PR when I get some time :)

**Comment by aeirola** [comment]
Fixed in version 0.3.1 thanks to @Tehnix contribution!

**Comment by di** [comment]
Thanks @aeirola and @Tehnix! Any idea when this will be released to NPM?

**Comment by aeirola** [comment]
@di Pushed the tag, but Travis failed to publish to NPM registry. Published the version manually now, would need to look into what is wrong in the automatic publish.
